-1:
  - "Its a Wicket!"
  - "Wow, an early wicket."
  - "Straight Down the Fielder's Throat, and he is out."
  - "A crucial wicket, that will be a game changer."
  - "In the air.., and a great catch, its out."

0:
  - "Defended, no run."
  - "In the block hole, no run."
  - "Straight to the fielder, no run."

1:
  - "That's a quick Single."
  - "Edged and taken."

2:
  - "That's a Proper Cricket Shot. A couple."
  - "In the gap that will be 2 runs."

3:
  - "A rare triple."
  - "Fielder saving the boundary there, 3 runs."
  - "Dropped!, That's gonna cost them, 3 runs."

4:
  - "A gentle shuffle and a clip, four for the taking"
  - "FOUR!, a great shot"
  - "A misfield and a boundary"
  - "Nice 4 runs, well played"

5:
  - "Huge wide, keeper misses and 4 byes"
  - "Four! and a no ball"

6:
  - "SIX runs, Elegant hit"
  - "That has taken the aerial route, and a Six!"
  - "Shot!, Over the long on"