## How to read this config?
### All the bowling/batting types along with their corresponding indexes are mapped below,
### Use the indexes to specify the best batting type at top, and worst type at bottom.
### Example, For Bouncer(index: 0), best shot might be Pull(index: 7), and worst can be Sweep(index: 5),
### 0:
###   -7
###   - ...
###   -5

## Bowling Cards Index:
# Bouncer: 0
# Outswinger: 1
# Off Cutter: 2
# Yorker :3
# Off Break: 4
# Inswinger: 5
# Leg Cutter: 6
# Slower Ball: 7
# Pace: 8
# Doosra: 9

## Batting Cards Index:
# Straight: 0
# Flick: 1
# LegLance: 2
# Long On: 3
# Square Cut: 4
# Sweep: 5
# CoverDrive: 6
# Pull: 7
# Scoop: 8
# UpperCut: 9


0:
  - 7
  - 9
  - 1
  - 3
  - 4
  - 6
  - 2
  - 0
  - 8
  - 5

1:
  - 1
  - 6
  - 0
  - 7
  - 3
  - 4
  - 9
  - 2
  - 5
  - 8

2:
  - 4
  - 1
  - 9
  - 0
  - 3
  - 6
  - 5
  - 8
  - 7
  - 2

3:
  - 0
  - 2
  - 1
  - 5
  - 4
  - 6
  - 8
  - 3
  - 7
  - 9

4:
  - 1
  - 6
  - 4
  - 0
  - 5
  - 2
  - 3
  - 9
  - 8
  - 7

5:
  - 3
  - 2
  - 0
  - 1
  - 6
  - 4
  - 7
  - 5
  - 8
  - 9

6:
  - 3
  - 2
  - 0
  - 6
  - 1
  - 7
  - 8
  - 4
  - 5
  - 9

7:
  - 0
  - 7
  - 6
  - 3
  - 8
  - 1
  - 2
  - 4
  - 5
  - 9

8:
  - 9
  - 1
  - 6
  - 0
  - 3
  - 5
  - 2
  - 7
  - 4
  - 8

9:
  - 8
  - 7
  - 5
  - 2
  - 3
  - 0
  - 1
  - 4
  - 6
  - 9
